spring.application.name=Spring-security

logging.level.org.springframework.security=DEBUG
spring.profiles.active=dev

# Security Configuration
spring.security.user.name=alex
spring.security.user.password=password
spring.security.user.roles=ADMIN

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:securitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allow H2 console access (for development only)
spring.h2.console.settings.web-allow-others=true

# Logging configuration
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.app=DEBUG


# Log file settings
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
#EMPTY THE LOG FILE BEFORE RUNNING THE APPLICATION
logging.logback.rollingpolicy.clean-history-on-start=true
